name: Trigger Deploy

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger dragonboy-devops-service
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.DEPLOY_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/DANG-PH/dragonboy-devops-service/dispatches \
            -d '{
              "event_type": "deploy",
              "client_payload": {
                "service": "pay-service",
                "dir": "/root/MICROSERVICE_PAY_SERVICE",
                "port": "3005",
                "skip_health_check": "false",
                "actor": "${{ github.actor }}",
                "commit": "${{ github.sha }}",
                "message": "${{ github.event.head_commit.message }}"
              }
            }'
